# Generated by Django 4.2.25 on 2025-10-14 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0008_freelancerprofile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('extracted_text', models.TextField(blank=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analyses', to='myapp.freelancerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
