# Generated by Django 5.2.6 on 2025-10-01 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="FreelancerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=120)),
                ("bio", models.TextField(blank=True, max_length=2000)),
                ("location_city", models.CharField(blank=True, max_length=80)),
                ("location_country", models.CharField(blank=True, max_length=80)),
                ("timezone", models.CharField(blank=True, max_length=50)),
                ("years_experience", models.PositiveSmallIntegerField(default=0)),
                ("hourly_rate", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "work_modes",
                    models.CharField(
                        choices=[
                            ("REMOTE", "Remote"),
                            ("HYBRID", "Hybrid"),
                            ("ONSITE", "Onsite"),
                        ],
                        default="REMOTE",
                        max_length=10,
                    ),
                ),
                (
                    "work_authorization",
                    models.CharField(
                        choices=[
                            ("INDIA_ONLY", "India Only"),
                            ("GLOBAL_REMOTE", "Global Remote"),
                            ("SPECIFIC_COUNTRIES", "Specific Countries"),
                        ],
                        default="GLOBAL_REMOTE",
                        max_length=30,
                    ),
                ),
                (
                    "resume_file",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("github_url", models.URLField(blank=True)),
                ("preferred_industries_note", models.TextField(blank=True)),
                ("travel_ready", models.BooleanField(default=False)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_whatsapp", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "avg_response_time_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("publications_link", models.URLField(blank=True)),
                ("portfolio_link", models.URLField(blank=True)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="freelancer_photos/"
                    ),
                ),
                (
                    "freelancer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="myapp.freelancer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.freelancerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FreelancerProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("role_title", models.CharField(blank=True, max_length=120)),
                ("summary", models.TextField(blank=True)),
                ("tech_stack", models.CharField(blank=True, max_length=255)),
                ("demo_url", models.URLField(blank=True)),
                ("repo_url", models.URLField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("impact_metrics", models.TextField(blank=True)),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.freelancerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="project_media/")),
                ("caption", models.CharField(blank=True, max_length=120)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="myapp.freelancerproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("link", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.freelancerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FreelancerLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("BASIC", "Basic"),
                            ("CONVERSATIONAL", "Conversational"),
                            ("FLUENT", "Fluent"),
                            ("NATIVE", "Native"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.freelancerprofile",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.language"
                    ),
                ),
            ],
            options={
                "unique_together": {("freelancer", "language")},
            },
        ),
        migrations.CreateModel(
            name="FreelancerRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.freelancerprofile",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.role"
                    ),
                ),
            ],
            options={
                "unique_together": {("freelancer", "role")},
            },
        ),
        migrations.CreateModel(
            name="FreelancerSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                            ("EXPERT", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("years", models.PositiveSmallIntegerField(default=0)),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.freelancerprofile",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.skill"
                    ),
                ),
            ],
            options={
                "unique_together": {("freelancer", "skill")},
            },
        ),
    ]
