# Generated by Django 5.2.6 on 2025-10-02 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_language_role_skill_freelancerprofile_achievement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruiterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_website", models.URLField(blank=True)),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IT", "IT / Software"),
                            ("HEALTHCARE", "Healthcare"),
                            ("EDUCATION", "Education"),
                            ("FINTECH", "FinTech"),
                            ("RETAIL", "Retail"),
                            ("OTHER", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("about_company", models.TextField(blank=True)),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                ("headquarters_city", models.CharField(blank=True, max_length=100)),
                ("headquarters_country", models.CharField(blank=True, max_length=100)),
                ("contact_email_alt", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("linkedin_url", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recruiter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="myapp.recruiter",
                    ),
                ),
            ],
        ),
    ]
