# Generated by Django 5.2.6 on 2025-10-03 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_recruiterprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FULLTIME", "Full-time"),
                            ("PARTTIME", "Part-time"),
                            ("CONTRACT", "Contract"),
                            ("INTERNSHIP", "Internship"),
                        ],
                        default="FULLTIME",
                        max_length=20,
                    ),
                ),
                (
                    "work_mode",
                    models.CharField(
                        choices=[
                            ("REMOTE", "Remote"),
                            ("HYBRID", "Hybrid"),
                            ("ONSITE", "Onsite"),
                        ],
                        default="ONSITE",
                        max_length=10,
                    ),
                ),
                ("location_city", models.CharField(blank=True, max_length=100)),
                ("location_country", models.CharField(blank=True, max_length=100)),
                ("experience_required", models.CharField(blank=True, max_length=20)),
                ("education_required", models.CharField(blank=True, max_length=120)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="myapp.recruiterprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("MUST_HAVE", "Must-have"),
                            ("NICE_TO_HAVE", "Nice to have"),
                        ],
                        default="MUST_HAVE",
                        max_length=12,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_skills",
                        to="myapp.job",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.skill"
                    ),
                ),
            ],
            options={
                "unique_together": {("job", "skill")},
            },
        ),
        migrations.AddField(
            model_name="job",
            name="skills_required",
            field=models.ManyToManyField(
                related_name="jobs", through="myapp.JobSkill", to="myapp.skill"
            ),
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover_letter", models.TextField(blank=True)),
                (
                    "resume",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/resumes/"
                    ),
                ),
                ("portfolio_url", models.URLField(blank=True)),
                (
                    "expected_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("availability_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under review"),
                            ("SHORTLISTED", "Shortlisted"),
                            ("REJECTED", "Rejected"),
                            ("HIRED", "Hired"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="myapp.freelancerprofile",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="myapp.job",
                    ),
                ),
            ],
            options={
                "unique_together": {("job", "freelancer")},
            },
        ),
    ]
