# Generated by Django 5.2.6 on 2025-10-03 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_add_application_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("SHORTLISTED", "Shortlisted"),
                            ("SHORTLISTED_ACCEPTED", "Shortlisted · Accepted"),
                            ("SHORTLISTED_DECLINED", "Shortlisted · Declined"),
                            ("SHORTLIST_EXPIRED", "Shortlist expired"),
                            ("INTERVIEW", "Interview"),
                            ("HIRED", "Hired"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="SUBMITTED",
                        max_length=32,
                    ),
                ),
                ("shortlisted_at", models.DateTimeField(blank=True, null=True)),
                ("shortlist_expires_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("interview_at", models.DateTimeField(blank=True, null=True)),
                (
                    "interview_link",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("interview_message", models.TextField(blank=True, null=True)),
                ("outcome_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow",
                        to="myapp.application",
                    ),
                ),
            ],
        ),
    ]
