# Generated by Django 4.2.25 on 2025-10-14 16:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_applicationflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_from_recruiter', to='myapp.application')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.freelancer')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=512)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.freelancer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
