# Generated by Django 4.2.25 on 2025-10-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_freelancerprofile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
